name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build ./Speckoz.Quiz/Quiz.API/Quiz.API.csproj --configuration Release
    - name: Curl
      run: curl 'https://api.ipify.org?format=json'
    - name: Run with dotnet
      run: dotnet run --project --urls="https://localhost:5001" ./Speckoz.Quiz/Quiz.API/Quiz.API.csproj
